### ISSUE TITLE
Get SQLAlchemy expression as data, not string

### ISSUE THREAD

**Issue by cbenz** [pglass/sqlitis#21]
Hi,

I would like to retrieve the SQLAlchemy expression as data. The `render` methods return strings.

Would you think it would be possible to do this? For example adding methods like `render`, potentially named `expression`, which would return a SQLAlchemy expression.

I just ask to have your opinion first, before (perhaps) doing it myself and submitting a pull request.

**Comment by pglass** [comment]
Before I get into the new feature: I'm not recommending this, but depending on your use case and if you fully trust your inputs, using the generally unsafe `eval(<str>)` (or the safer `ast.literal_eval`) on the current output of the render method could work for you. It will give you a SQLAlchemy expression, though use of `eval` is generally not recommended, considered unsafe, bad practice, etc.

As far as adding behavior to render to an expression, I haven't thought through it fully, but it should be straightforward. I would want the two methods named `render_string` and `render_expression` (and there is probably better code organization than dangling two methods off of all the sqlitis model classes I have, but that's a separate thing).

For example, it's easy to construct SQLAlchemy expressions,

```python
>>> from sqlalchemy.sql import select, text
>>> expr = select([text('col')]).select_from(text('table')).where(text('col = 1'))
>>> print(expr)
SELECT col
FROM table
WHERE col = 1
```

But, that uses `text('table')` and `text('col')` because we wouldn't have the user's actual SQLAlchemy objects to work with. Typical usage of SQLAlchemy would have a real [Table object](https://docs.sqlalchemy.org/en/latest/core/metadata.html#sqlalchemy.schema.Table), and you'd just write `select(table.c.col)` and `select_from(table)` instead.

So an initial version could use the `text('table')` approach, and then later enhancement would be the ability to receive user-defined SQLAlchemy objects that sqlitis can incorporate while building up the expression.

**Comment by cbenz** [comment]
Thanks for your answer :)

In the meantime I found another solution for my need. I close this issue because it answers my question.
